name: create-issue-on-push
run-name: Create Issue on push
on:
  push:
    branches:
      - main
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Run create issue script
        run: |
          gh issue create --title "Test Issue" --body "Testing if I can create issues from workflow" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}