name: create-issue-on-push
run-name: Create Issue on push
on:
  push:
    branches:
      - main
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Run create issue script
        run: |
          chmod +x ./.github/scripts/create-issue.sh
          ./.github/scripts/create-issue.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_REPONAME: ${{ github.event.repository.name }}