name: create-issue-on-push
run-name: Create Issue on push
on:
  push:
    branches:
      - main
jobs:
  creat-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run create issue script
        run: | 
          chmod +x ./.github/scripts/create-issue.sh
          ./.github/scripts/create-issue.sh
        shell: bash